// Image strategy: small curated pool of well-known Unsplash fashion photos
// (popular, high-view-count IDs unlikely to be deleted). Each pool entry is
// reused across multiple similar products. The frontend has an onError
// fallback to a default illustration if any URL ever 404s.
const u = (id: string, w = 800) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=80`;

// Curated Unsplash photo IDs grouped by garment type.
const IMG = {
  // Shirts & tops
  whiteTee: "1521572163474-6864f9cf17ab",
  blackTee: "1503341504253-dff4815485f1",
  oxfordShirt: "1620799140408-edc6dcb6d633",
  flannelShirt: "1608030609295-a581b8f46672",
  hoodie: "1556821840-3a63f95609a7",
  sweater: "1576871337632-b9aef4c17ab9",
  poloShirt: "1583743814966-8936f5b7be1a",
  blouse: "1564859228033-8c5b59569e1d",
  tank: "1571945153237-4929e783af4a",

  // Pants & bottoms
  blueJeans: "1542272604-787c3835535d",
  blackJeans: "1604176354204-9268737828e4",
  chinos: "1473966968600-fa801b78a3ce",
  trousers: "1593030761757-71fae45fa0e7",
  joggers: "1552902865-b72c031ac5ea",
  cargoPants: "1624378439575-d8705ad7ae80",
  shorts: "1591047139829-d91aecb6caea",
  cordsTrousers: "1598522325074-042db73aa4e5",

  // Outerwear
  denimJacket: "1576995853123-5a10305d93c0",
  leatherJacket: "1551028719-00167b16eac5",
  parka: "1539533018447-63fcce2678e3",
  trenchCoat: "1577900232427-18219b9166a0",
  bomber: "1591047139756-eb1212c8edb6",
  puffer: "1611312449412-6cefac5dc3e4",
  windbreaker: "1565693413579-8ff3fdc1b03d",
  peaCoat: "1553754538-466add009c05",

  // Accessories
  belt: "1624378439575-d8705ad7ae80",
  scarf: "1601379329542-31c59ab3ca56",
  cap: "1588850561407-ed78c282e89b",
  beanie: "1576871337622-98d48d1cf531",
  bag: "1591561954557-26941169b49e",
  sunglasses: "1511499767150-a48a237f0083",
  wallet: "1623998021446-45a51d8f3a96",
  gloves: "1612462867773-b4d3b1f7e735",
  watch: "1523275335684-37898b6baf30",

  // Category covers
  catShirts: "1489987707025-afc232f7ea0f",
  catPants: "1542272604-787c3835535d",
  catOuterwear: "1551028719-00167b16eac5",
  catAccessories: "1611652022419-a9419f74343d",
} as const;

const T = {
  createdAt: "2025-05-15 21:00:00.000000+03",
  updatedAt: "2025-05-15 21:00:00.000000+03",
};

const SHIRTS = "1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d";
const PANTS = "2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e";
const OUTERWEAR = "3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f";
const ACCESSORIES = "4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a";

export const categories = [
  { id: SHIRTS, name: "Shirts & Tops", imageUrl: u(IMG.catShirts), ...T },
  { id: PANTS, name: "Pants & Bottoms", imageUrl: u(IMG.catPants), ...T },
  { id: OUTERWEAR, name: "Outerwear", imageUrl: u(IMG.catOuterwear), ...T },
  { id: ACCESSORIES, name: "Accessories", imageUrl: u(IMG.catAccessories), ...T },
];

const topSizes = [
  { size: "XS", chestCm: 88, waistCm: 76 },
  { size: "S", chestCm: 96, waistCm: 84 },
  { size: "M", chestCm: 104, waistCm: 92 },
  { size: "L", chestCm: 112, waistCm: 100 },
  { size: "XL", chestCm: 120, waistCm: 108 },
];

const bottomSizes = [
  { size: "28", waistCm: 74, inseamCm: 78 },
  { size: "30", waistCm: 78, inseamCm: 79 },
  { size: "32", waistCm: 84, inseamCm: 80 },
  { size: "34", waistCm: 90, inseamCm: 81 },
  { size: "36", waistCm: 96, inseamCm: 82 },
];

const trouserSizes = [
  { size: "S", waistCm: 72, hipCm: 94, inseamCm: 77 },
  { size: "M", waistCm: 78, hipCm: 100, inseamCm: 78 },
  { size: "L", waistCm: 84, hipCm: 106, inseamCm: 79 },
  { size: "XL", waistCm: 90, hipCm: 112, inseamCm: 80 },
];

const jacketSizes = [
  { size: "S", chestCm: 100, waistCm: 88 },
  { size: "M", chestCm: 108, waistCm: 96 },
  { size: "L", chestCm: 116, waistCm: 104 },
  { size: "XL", chestCm: 124, waistCm: 112 },
];

const beltSizes = [
  { size: "S", waistCm: 74 },
  { size: "M", waistCm: 82 },
  { size: "L", waistCm: 90 },
  { size: "XL", waistCm: 98 },
];

const oneSize = [{ size: "One Size" }];
const adjustable = [{ size: "Adjustable" }];

export const products = [
  // ───────────── Shirts & Tops ─────────────
  {
    id: "5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b",
    name: "Classic Oxford Shirt",
    categoryId: SHIRTS,
    price: 45.0,
    description: "Crisp cotton Oxford with button-down collar and tailored fit.",
    stock: 120,
    fitType: "regular",
    recommendationTags: ["tops", "shirts", "smart-casual", "tailored"],
    sizeChartJson: topSizes,
    imageUrl: u(IMG.oxfordShirt),
    ...T,
  },
  {
    id: "6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c",
    name: "Graphic Crewneck Tee",
    categoryId: SHIRTS,
    price: 25.99,
    description: "Soft cotton tee with a modern graphic print on the front.",
    stock: 200,
    fitType: "oversized",
    recommendationTags: ["tops", "tees", "casual", "bold"],
    sizeChartJson: topSizes,
    imageUrl: u(IMG.blackTee),
    ...T,
  },
  {
    id: "7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d",
    name: "Silk Chiffon Blouse",
    categoryId: SHIRTS,
    price: 65.5,
    description: "Elegant silk chiffon blouse with ruffled neckline.",
    stock: 80,
    fitType: "regular",
    recommendationTags: ["tops", "blouses", "dressy", "draped", "flowing"],
    sizeChartJson: topSizes,
    imageUrl: u(IMG.blouse),
    ...T,
  },
  {
    id: "a1b2c3d4-1111-4111-9111-aaaaaaaaaaa1",
    name: "Striped Polo Shirt",
    categoryId: SHIRTS,
    price: 38.0,
    description: "Pique cotton polo with horizontal stripes and ribbed collar.",
    stock: 150,
    fitType: "regular",
    recommendationTags: ["tops", "polo", "smart-casual", "stripes"],
    sizeChartJson: topSizes,
    imageUrl: u(IMG.poloShirt),
    ...T,
  },
  {
    id: "a1b2c3d4-1111-4111-9111-aaaaaaaaaaa2",
    name: "Linen Button-Up",
    categoryId: SHIRTS,
    price: 52.0,
    description: "Lightweight linen button-up, breathable for warm days.",
    stock: 95,
    fitType: "regular",
    recommendationTags: ["tops", "shirts", "summer", "linen", "casual"],
    sizeChartJson: topSizes,
    imageUrl: u(IMG.flannelShirt),
    ...T,
  },
  {
    id: "a1b2c3d4-1111-4111-9111-aaaaaaaaaaa3",
    name: "Hooded Sweatshirt",
    categoryId: SHIRTS,
    price: 49.0,
    description: "Brushed-fleece hoodie with kangaroo pocket and drawcord hood.",
    stock: 175,
    fitType: "oversized",
    recommendationTags: ["tops", "hoodie", "casual", "athleisure"],
    sizeChartJson: topSizes,
    imageUrl: u(IMG.hoodie),
    ...T,
  },
  {
    id: "a1b2c3d4-1111-4111-9111-aaaaaaaaaaa4",
    name: "Knit Turtleneck Sweater",
    categoryId: SHIRTS,
    price: 72.0,
    description: "Merino wool blend turtleneck with ribbed hem and cuffs.",
    stock: 90,
    fitType: "slim",
    recommendationTags: ["tops", "knitwear", "winter", "fitted"],
    sizeChartJson: topSizes,
    imageUrl: u(IMG.sweater),
    ...T,
  },
  {
    id: "a1b2c3d4-1111-4111-9111-aaaaaaaaaaa5",
    name: "Athletic Tank Top",
    categoryId: SHIRTS,
    price: 19.99,
    description: "Moisture-wicking tank with mesh side panels for ventilation.",
    stock: 220,
    fitType: "slim",
    recommendationTags: ["tops", "athletic", "active", "fitted"],
    sizeChartJson: topSizes,
    imageUrl: u(IMG.tank),
    ...T,
  },
  {
    id: "a1b2c3d4-1111-4111-9111-aaaaaaaaaaa6",
    name: "Flannel Plaid Shirt",
    categoryId: SHIRTS,
    price: 56.0,
    description: "Brushed flannel in classic buffalo plaid, snap-button front.",
    stock: 110,
    fitType: "regular",
    recommendationTags: ["tops", "flannel", "fall", "casual", "plaid"],
    sizeChartJson: topSizes,
    imageUrl: u(IMG.flannelShirt),
    ...T,
  },

  // ───────────── Pants & Bottoms ─────────────
  {
    id: "8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e",
    name: "Slim Fit Denim Jeans",
    categoryId: PANTS,
    price: 55.0,
    description: "Stretch denim jeans with a slim cut and dark wash finish.",
    stock: 100,
    fitType: "slim",
    recommendationTags: ["bottoms", "jeans", "denim", "fitted"],
    sizeChartJson: bottomSizes,
    imageUrl: u(IMG.blueJeans),
    ...T,
  },
  {
    id: "9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f",
    name: "Khaki Chino Pants",
    categoryId: PANTS,
    price: 49.95,
    description: "Lightweight chinos with tapered leg and five-pocket styling.",
    stock: 150,
    fitType: "regular",
    recommendationTags: ["bottoms", "chinos", "casual", "tailored"],
    sizeChartJson: bottomSizes,
    imageUrl: u(IMG.chinos),
    ...T,
  },
  {
    id: "0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a",
    name: "High-Waisted Wide Trousers",
    categoryId: PANTS,
    price: 59.99,
    description: "Chic high-waisted trousers with wide leg and belt loops.",
    stock: 70,
    fitType: "regular",
    recommendationTags: ["bottoms", "trousers", "workwear", "wide-leg", "structured"],
    sizeChartJson: trouserSizes,
    imageUrl: u(IMG.trousers),
    ...T,
  },
  {
    id: "b2c3d4e5-2222-4222-9222-bbbbbbbbbbb1",
    name: "Cargo Utility Pants",
    categoryId: PANTS,
    price: 64.0,
    description: "Cotton-blend cargo pants with reinforced pockets at the thigh.",
    stock: 130,
    fitType: "regular",
    recommendationTags: ["bottoms", "cargo", "utility", "casual"],
    sizeChartJson: bottomSizes,
    imageUrl: u(IMG.cargoPants),
    ...T,
  },
  {
    id: "b2c3d4e5-2222-4222-9222-bbbbbbbbbbb2",
    name: "Wide-Leg Linen Pants",
    categoryId: PANTS,
    price: 68.0,
    description: "Breezy linen pants with a relaxed wide leg and elastic waist.",
    stock: 80,
    fitType: "oversized",
    recommendationTags: ["bottoms", "linen", "summer", "wide-leg", "flowing"],
    sizeChartJson: trouserSizes,
    imageUrl: u(IMG.cordsTrousers),
    ...T,
  },
  {
    id: "b2c3d4e5-2222-4222-9222-bbbbbbbbbbb3",
    name: "Athletic Tapered Joggers",
    categoryId: PANTS,
    price: 42.5,
    description: "Soft fleece joggers with tapered leg and elastic ankle cuffs.",
    stock: 200,
    fitType: "slim",
    recommendationTags: ["bottoms", "joggers", "active", "athleisure", "fitted"],
    sizeChartJson: bottomSizes,
    imageUrl: u(IMG.joggers),
    ...T,
  },
  {
    id: "b2c3d4e5-2222-4222-9222-bbbbbbbbbbb4",
    name: "Pleated Dress Pants",
    categoryId: PANTS,
    price: 78.0,
    description: "Wool-blend dress pants with single pleat and cuffed hem.",
    stock: 65,
    fitType: "regular",
    recommendationTags: ["bottoms", "dress-pants", "workwear", "tailored"],
    sizeChartJson: trouserSizes,
    imageUrl: u(IMG.trousers),
    ...T,
  },
  {
    id: "b2c3d4e5-2222-4222-9222-bbbbbbbbbbb5",
    name: "Cropped Skinny Jeans",
    categoryId: PANTS,
    price: 58.0,
    description: "High-rise skinny jeans cropped at the ankle with raw hem.",
    stock: 115,
    fitType: "slim",
    recommendationTags: ["bottoms", "jeans", "denim", "cropped", "fitted"],
    sizeChartJson: bottomSizes,
    imageUrl: u(IMG.blackJeans),
    ...T,
  },
  {
    id: "b2c3d4e5-2222-4222-9222-bbbbbbbbbbb6",
    name: "Corduroy Trousers",
    categoryId: PANTS,
    price: 62.0,
    description: "Vintage-feel corduroy trousers with straight leg and side pockets.",
    stock: 75,
    fitType: "regular",
    recommendationTags: ["bottoms", "corduroy", "fall", "vintage"],
    sizeChartJson: trouserSizes,
    imageUrl: u(IMG.cordsTrousers),
    ...T,
  },

  // ───────────── Outerwear ─────────────
  {
    id: "1e2f3a4b-5c6d-7e8f-9a0b-1c2d3e4f5a6b",
    name: "Classic Denim Jacket",
    categoryId: OUTERWEAR,
    price: 75.0,
    description: "Rugged denim jacket with button closure and chest flap pockets.",
    stock: 90,
    fitType: "regular",
    recommendationTags: ["outerwear", "jackets", "casual", "structured"],
    sizeChartJson: jacketSizes,
    imageUrl: u(IMG.denimJacket),
    ...T,
  },
  {
    id: "2f3a4b5c-6d7e-8f9a-0b1c-2d3e4f5a6b7c",
    name: "Leather Biker Jacket",
    categoryId: OUTERWEAR,
    price: 199.99,
    description: "Genuine leather biker jacket with asymmetrical zip and quilted shoulders.",
    stock: 55,
    fitType: "slim",
    recommendationTags: ["outerwear", "jackets", "premium", "fitted", "bold"],
    sizeChartJson: jacketSizes,
    imageUrl: u(IMG.leatherJacket),
    ...T,
  },
  {
    id: "3a4b5c6d-7e8f-9a0b-1c2d-3e4f5a6b7c8d",
    name: "Hooded Parka Coat",
    categoryId: OUTERWEAR,
    price: 120.0,
    description: "Insulated parka with faux fur hood and water-resistant shell.",
    stock: 40,
    fitType: "oversized",
    recommendationTags: ["outerwear", "coats", "winter", "longline"],
    sizeChartJson: jacketSizes,
    imageUrl: u(IMG.parka),
    ...T,
  },
  {
    id: "c3d4e5f6-3333-4333-9333-ccccccccccc1",
    name: "Wool Pea Coat",
    categoryId: OUTERWEAR,
    price: 165.0,
    description: "Heritage wool pea coat with double-breasted front and notched lapels.",
    stock: 50,
    fitType: "regular",
    recommendationTags: ["outerwear", "coats", "wool", "tailored", "structured"],
    sizeChartJson: jacketSizes,
    imageUrl: u(IMG.peaCoat),
    ...T,
  },
  {
    id: "c3d4e5f6-3333-4333-9333-ccccccccccc2",
    name: "Quilted Puffer Jacket",
    categoryId: OUTERWEAR,
    price: 95.0,
    description: "Lightweight down puffer with packable design and adjustable hood.",
    stock: 110,
    fitType: "regular",
    recommendationTags: ["outerwear", "puffer", "winter", "down"],
    sizeChartJson: jacketSizes,
    imageUrl: u(IMG.puffer),
    ...T,
  },
  {
    id: "c3d4e5f6-3333-4333-9333-ccccccccccc3",
    name: "Trench Coat",
    categoryId: OUTERWEAR,
    price: 185.0,
    description: "Cotton-gabardine trench with belted waist and storm flap.",
    stock: 45,
    fitType: "regular",
    recommendationTags: ["outerwear", "coats", "tailored", "belted", "longline"],
    sizeChartJson: jacketSizes,
    imageUrl: u(IMG.trenchCoat),
    ...T,
  },
  {
    id: "c3d4e5f6-3333-4333-9333-ccccccccccc4",
    name: "Bomber Jacket",
    categoryId: OUTERWEAR,
    price: 89.0,
    description: "Satin-finish bomber with ribbed cuffs, hem, and zip front.",
    stock: 95,
    fitType: "regular",
    recommendationTags: ["outerwear", "bomber", "casual"],
    sizeChartJson: jacketSizes,
    imageUrl: u(IMG.bomber),
    ...T,
  },
  {
    id: "c3d4e5f6-3333-4333-9333-ccccccccccc5",
    name: "Lightweight Windbreaker",
    categoryId: OUTERWEAR,
    price: 58.0,
    description: "Packable windbreaker with mesh lining and elastic cuffs.",
    stock: 140,
    fitType: "regular",
    recommendationTags: ["outerwear", "windbreaker", "active", "lightweight"],
    sizeChartJson: jacketSizes,
    imageUrl: u(IMG.windbreaker),
    ...T,
  },
  {
    id: "c3d4e5f6-3333-4333-9333-ccccccccccc6",
    name: "Sherpa Fleece Vest",
    categoryId: OUTERWEAR,
    price: 64.0,
    description: "Cozy sherpa-lined vest with zip pockets and stand collar.",
    stock: 85,
    fitType: "regular",
    recommendationTags: ["outerwear", "vest", "fleece", "winter", "layered"],
    sizeChartJson: jacketSizes,
    imageUrl: u(IMG.puffer),
    ...T,
  },

  // ───────────── Accessories ─────────────
  {
    id: "4b5c6d7e-8f9a-0b1c-2d3e-4f5a6b7c8d9e",
    name: "Leather Waist Belt",
    categoryId: ACCESSORIES,
    price: 35.0,
    description: "Genuine leather belt with adjustable metal buckle.",
    stock: 180,
    fitType: "one-size",
    recommendationTags: ["accessories", "belt", "waist", "belted"],
    sizeChartJson: beltSizes,
    imageUrl: u(IMG.belt),
    ...T,
  },
  {
    id: "5c6d7e8f-9a0b-1c2d-3e4f-5a6b7c8d9e0f",
    name: "Wool Knit Scarf",
    categoryId: ACCESSORIES,
    price: 22.5,
    description: "Soft wool scarf with ribbed knit and fringed edges.",
    stock: 140,
    fitType: "one-size",
    recommendationTags: ["accessories", "scarf", "winter", "draped"],
    sizeChartJson: oneSize,
    imageUrl: u(IMG.scarf),
    ...T,
  },
  {
    id: "6d7e8f9a-0b1c-2d3e-4f5a-6b7c8d9e0f1a",
    name: "Cotton Baseball Cap",
    categoryId: ACCESSORIES,
    price: 18.0,
    description: "Adjustable cotton cap with embroidered logo and curved brim.",
    stock: 210,
    fitType: "adjustable",
    recommendationTags: ["accessories", "cap", "headwear"],
    sizeChartJson: adjustable,
    imageUrl: u(IMG.cap),
    ...T,
  },
  {
    id: "d4e5f6a7-4444-4444-9444-ddddddddddd1",
    name: "Wool Beanie",
    categoryId: ACCESSORIES,
    price: 19.5,
    description: "Soft merino-blend beanie with cuffed brim.",
    stock: 175,
    fitType: "one-size",
    recommendationTags: ["accessories", "beanie", "winter", "headwear"],
    sizeChartJson: oneSize,
    imageUrl: u(IMG.beanie),
    ...T,
  },
  {
    id: "d4e5f6a7-4444-4444-9444-ddddddddddd2",
    name: "Leather Crossbody Bag",
    categoryId: ACCESSORIES,
    price: 89.0,
    description: "Compact leather crossbody with adjustable strap and zip closure.",
    stock: 95,
    fitType: "one-size",
    recommendationTags: ["accessories", "bag", "leather", "premium"],
    sizeChartJson: oneSize,
    imageUrl: u(IMG.bag),
    ...T,
  },
  {
    id: "d4e5f6a7-4444-4444-9444-ddddddddddd3",
    name: "Aviator Sunglasses",
    categoryId: ACCESSORIES,
    price: 48.0,
    description: "Classic aviator sunglasses with polarized lenses and metal frame.",
    stock: 160,
    fitType: "one-size",
    recommendationTags: ["accessories", "sunglasses", "summer"],
    sizeChartJson: oneSize,
    imageUrl: u(IMG.sunglasses),
    ...T,
  },
  {
    id: "d4e5f6a7-4444-4444-9444-ddddddddddd4",
    name: "Silk Pocket Square",
    categoryId: ACCESSORIES,
    price: 24.0,
    description: "Hand-rolled silk pocket square in geometric pattern.",
    stock: 220,
    fitType: "one-size",
    recommendationTags: ["accessories", "pocket-square", "dressy", "tailored"],
    sizeChartJson: oneSize,
    imageUrl: u(IMG.scarf),
    ...T,
  },
  {
    id: "d4e5f6a7-4444-4444-9444-ddddddddddd5",
    name: "Leather Bifold Wallet",
    categoryId: ACCESSORIES,
    price: 55.0,
    description: "Slim bifold wallet in full-grain leather with six card slots.",
    stock: 130,
    fitType: "one-size",
    recommendationTags: ["accessories", "wallet", "leather"],
    sizeChartJson: oneSize,
    imageUrl: u(IMG.wallet),
    ...T,
  },
  {
    id: "d4e5f6a7-4444-4444-9444-ddddddddddd6",
    name: "Knitted Gloves",
    categoryId: ACCESSORIES,
    price: 16.5,
    description: "Cable-knit gloves with touchscreen-compatible fingertips.",
    stock: 195,
    fitType: "one-size",
    recommendationTags: ["accessories", "gloves", "winter"],
    sizeChartJson: oneSize,
    imageUrl: u(IMG.gloves),
    ...T,
  },
];
